package com.hoavu.camerax.ui.theme

import androidx.compose.ui.graphics.Color

object CameraXColors {
    val White = Color.White
    val Black = Color.Black
    val Transparent = Color.Transparent
}

val light_primary = Color(0xFF7D5800)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFFFDEA9)
val light_onPrimaryContainer = Color(0xFF271900)
val light_secondary = Color(0xFF6D5C3F)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFF7DFBB)
val light_onSecondaryContainer = Color(0xFF251A04)
val light_tertiary = Color(0xFF4D6544)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFCFEBC0)
val light_onTertiaryContainer = Color(0xFF0B2006)
val light_error = Color(0xFFBA1A1A)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFFFBFF)
val light_onBackground = Color(0xFF1F1B16)
val light_surface = Color(0xFFFFFBFF)
val light_onSurface = Color(0xFF1F1B16)
val light_surfaceVariant = Color(0xFFEEE1CF)
val light_onSurfaceVariant = Color(0xFF4E4639)
val light_outline = Color(0xFF807667)
val light_inverseOnSurface = Color(0xFFF8EFE7)
val light_inverseSurface = Color(0xFF34302A)
val light_inversePrimary = Color(0xFFF8BD49)
val light_shadow = Color(0xFF000000)
val light_surfaceTint = Color(0xFF7D5800)
val light_outlineVariant = Color(0xFFD1C5B4)
val light_scrim = Color(0xFF000000)

val dark_primary = Color(0xFFF8BD49)
val dark_onPrimary = Color(0xFF422D00)
val dark_primaryContainer = Color(0xFF5E4200)
val dark_onPrimaryContainer = Color(0xFFFFDEA9)
val dark_secondary = Color(0xFFDAC3A1)
val dark_onSecondary = Color(0xFF3C2E15)
val dark_secondaryContainer = Color(0xFF54442A)
val dark_onSecondaryContainer = Color(0xFFF7DFBB)
val dark_tertiary = Color(0xFFB3CEA6)
val dark_onTertiary = Color(0xFF203619)
val dark_tertiaryContainer = Color(0xFF364D2E)
val dark_onTertiaryContainer = Color(0xFFCFEBC0)
val dark_error = Color(0xFFFFB4AB)
val dark_errorContainer = Color(0xFF93000A)
val dark_onError = Color(0xFF690005)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF1F1B16)
val dark_onBackground = Color(0xFFEAE1D9)
val dark_surface = Color(0xFF1F1B16)
val dark_onSurface = Color(0xFFEAE1D9)
val dark_surfaceVariant = Color(0xFF4E4639)
val dark_onSurfaceVariant = Color(0xFFD1C5B4)
val dark_outline = Color(0xFF9A8F80)
val dark_inverseOnSurface = Color(0xFF1F1B16)
val dark_inverseSurface = Color(0xFFEAE1D9)
val dark_inversePrimary = Color(0xFF7D5800)
val dark_shadow = Color(0xFF000000)
val dark_surfaceTint = Color(0xFFF8BD49)
val dark_outlineVariant = Color(0xFF4E4639)
val dark_scrim = Color(0xFF000000)


val seed = Color(0xFF7D5800)